# Generated by Django 3.1.7 on 2021-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210405_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bussiness_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
