# Generated by Django 3.1.7 on 2021-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_bussiness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bussiness_name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
