# Generated by Django 3.1.7 on 2021-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210408_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bussiness_name',
            field=models.CharField(max_length=50),
        ),
    ]
