# Generated by Django 3.1.7 on 2021-04-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210408_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bussiness_name',
        ),
    ]
