# Generated by Django 3.1.7 on 2021-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210408_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
