# Generated by Django 3.1.1 on 2021-04-14 10:17

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210410_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='')),
            ],
        ),
    ]
