# Generated by Django 3.1.1 on 2021-04-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='change',
        ),
    ]
