# Generated by Django 3.2 on 2021-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('mob', 'Mobiles'), ('comp', 'Computers'), ('ele', 'Electronics'), ('soft', 'Software'), ('game', 'Gaming')], max_length=50, null=True),
        ),
    ]
