# Generated by Django 3.2 on 2021-04-11 09:10

from django.db import migrations


def create_data(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product(
        name="Amazon Echo Dot 3rd Generation",
        category="Electronics",
        description="Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
        price="4499.00",
        countInStock="7"
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
